### ISSUE TITLE
Missing types for manifest globals

### ISSUE THREAD

**Issue by napei** [overextended/cfxlua-vscode#10]
Am I missing something? Manifest globals appear to be undefined. I'm trying to avoid turning off `undefined-global` where possible. I could also just ignore `**/fxmanifest.lua` but I think providing these types would be straightforward?

![image](https://user-images.githubusercontent.com/8946502/193943942-bd53e996-71a2-461e-800c-915227814b89.png)

**Comment by thelindat** [comment]
I’d rather not define global functions just for fxmanifest but haven’t come up with an alternative yet. fxmanifest also accepts any random metadata so any warnings aren’t accurate anyway.

**Comment by napei** [comment]
Could specifically disable `undefined-global` just for `fxmanifest.lua` or `__resource.lua` files. I don't know if this extension can force sumneko's lua to do that or not. Perhaps a plugin?
