### ISSUE TITLE
Support vector unpacking (somehow)

### ISSUE THREAD

**Issue by napei** [overextended/cfxlua-vscode#11]
Probably a challenge to implement, but support for, or at least overload functions for vector unpacking would be nice to have if possible.

Current solution is `missing-parameter` but that shadows a bunch of other actual errors for things like providing no parameters to a function, or implied `false`. On the flipside, `coords.x, coords.y, coords.z` is probably more semantically correct anyway.

![image](https://user-images.githubusercontent.com/8946502/193944321-75dd5827-b233-44cb-a046-37380dd939f8.png)

**Comment by thelindat** [comment]
I only use oal which doesn’t support vector unpacking anyway. Supporting this sounds like a nightmare and I would prefer strict adherence to arguments over the confusion and difficulty unpacking would entail.

I’m also no way near smart enough to figure out how to implement that, and gottfried found it tedious to keep it in.
