### ISSUE TITLE
suggestion: ignore strings obfuscated by CFX.RE

### ISSUE THREAD

**Issue by MatinHQ** [overextended/cfxlua-vscode#16]
If you obfuscate a script at keymaster.fivem.net, you will get thousands of errors, it would be nice if addon could ignore these kinds of strings.

![image](https://user-images.githubusercontent.com/22664859/199470109-ff473c75-3a66-40c0-ba8f-7ada351712f0.png)

**Comment by DokaDoka** [comment]
nice, add the folder to "Lua.workspace.ignoreDir" in `settings.json` I doubt anyone will be willing to implement this

**Comment by MatinHQ** [comment]
I am already aware of this but when you are working on a large work space you cant just add them one by one and I dont want to ignore entire folder

**Comment by MatinHQ** [comment]
Thanks <3
