### ISSUE TITLE
Ability to switch native db for RedM support

### ISSUE THREAD

**Issue by Bobertsawesome** [overextended/cfxlua-vscode#18]
I intended on forking and doing this myself, but I have no idea how this script gets the fivem native DB after looking through the code. Over my head.

But in any case, here is the current RedM DB: https://raw.githubusercontent.com/alloc8or/rdr3-nativedb-data/master/natives.json

**Comment by TasoOneAsia** [comment]
See [this](https://github.com/TasoOneAsia/JetbrainIDE-CFX.RE/blob/b05b2fa69897626f2f44b92e0af7844ed366b0ea/main.ts#L15-L24), for how type definitions are sourced.

**Comment by thelindat** [comment]
Planned, just been lazy.

> I have no idea how this script gets the fivem native DB after looking through the code.

There's no workflow setup so right now I just generate manually using https://github.com/thelindat/JetbrainIDE-CFX.RE, drop into my local repository, and publish to vscode from there.

**Comment by Bobertsawesome** [comment]
Ahh ok that makes sense then. I was seriously scratching my head lol. Saw nothing of a reference. I forked a popular fivem extension to be used with redm natives, just needed some new pointers.  It automatically fetches the db each startup. Here’s that implementation https://github.com/UnderworldServers/redm-vscode

**Comment by thelindat** [comment]
Being a bit lazy with it, but if you edit your workspace settings.json with `"cfxlua.game": "rdr3"` it'll unload FiveM natives and load RedM's.

**Comment by Bobertsawesome** [comment]
Thanks for the info. I’ll try it out soon. On Dec 2, 2022, at 1:20 AM, Linden ***@***.***> wrote:﻿
Being a bit lazy with it, but if you edit your workspace settings.json with "cfxlua.game": "rdr3" it'll unload FiveM natives and load RedM's.
