### ISSUE TITLE
Features partially working

### ISSUE THREAD

**Issue by rdelian** [overextended/cfxlua-vscode#27]
Cfx's LuaGLM features are not recognised

**CfxLua:** `v1.7.3`
**Lua(sumneko):** `v3.7.0`
**VSCode:** `v1.81.1`

![image](https://github.com/overextended/cfxlua-vscode/assets/25958136/631e1724-77a9-4956-a653-869986fb2ff6)

**Comment by thelindat** [comment]
Afaik this is weirdness with settings.json or .luarc.json in a workspace or directory overwriting user settings.
I'm probably going to look at moving to LuaAddons through LLS just to limit some issues with adding libraries/plugin through an extension.

**Comment by rdelian** [comment]
Well, it _"magically"_ started working again just 10 minutes after posting this

\*_magically = I forgot what I did_
