### ISSUE TITLE
External Editor Support

### ISSUE THREAD

**Issue by Bobrokus** [overextended/cfxlua-vscode#33]
I really like the extension and I would like to use it outside of VSCode in an external code editor like Helix (or Vim/Nvim).

This could be achieved by creating a standalone CLI version of the language server.

**Comment by thelindat** [comment]
> This could be achieved by creating a standalone CLI version of the language server.

The language server is from https://github.com/LuaLS/lua-language-server and is not dependant on vscode. This resource just installs the [vscode-lua](https://github.com/LuaLS/vscode-lua) extension, includes [fivem-lls-addon](https://github.com/overextended/fivem-lls-addon/tree/main), and changes some settings for you.

See the links below to use any code editor.
- https://luals.github.io/#neovim-install
- https://luals.github.io/#other-install

Download [fivem-lls-addon](https://github.com/overextended/fivem-lls-addon/tree/main) and configure the libraries and plugin in a [.luarc.json](https://luals.github.io/wiki/configuration/#luarcjson-file) file in your project root to include those paths.

**Comment by Bobrokus** [comment]
@thelindat Hey, thanks for the response!

Actually, I already have https://github.com/LuaLS/lua-language-server installed and setup with Helix. I found this addon: https://github.com/ProjectTH/fivem-lls-addon, and I was wondering if it's somehow related to [your addon](https://github.com/overextended/fivem-lls-addon)

**Comment by thelindat** [comment]
> I found this addon: https://github.com/ProjectTH/fivem-lls-addon, and I was wondering if it's somehow related to [your addon](https://github.com/overextended/fivem-lls-addon)

For whatever reason they forked my plugin, made objectively worse native codegen, and then PR'd it to [LLS-Addons](https://github.com/LuaLS/LLS-Addons) which is a vscode addon viewer.

**Comment by Bobrokus** [comment]
> For whatever reason they forked my plugin, made objectively worse native codegen, and then PR'd it to [LLS-Addons](https://github.com/LuaLS/LLS-Addons) which is a vscode addon viewer.

Oh. That's what I thought. It's a shame. Good to know though!

**Comment by Bobrokus** [comment]
> Download [fivem-lls-addon](https://github.com/overextended/fivem-lls-addon/tree/main?rgh-link-date=2024-05-13T19%3A15%3A46Z) and configure the libraries and plugin in a [.luarc.json](https://luals.github.io/wiki/configuration/#luarcjson-file) file in your project root to include those paths.

I've successfully configured everything and it works amazingly! Thanks for the advice

**Comment by Bobrokus** [comment]
> This resource just installs the [vscode-lua](https://github.com/LuaLS/vscode-lua) extension, includes [fivem-lls-addon](https://github.com/overextended/fivem-lls-addon/tree/main?rgh-link-date=2024-05-13T19%3A15%3A46Z), and changes some settings for you.

> Download [fivem-lls-addon](https://github.com/overextended/fivem-lls-addon/tree/main?rgh-link-date=2024-05-13T19%3A15%3A46Z) and configure the libraries and plugin in a [.luarc.json](https://luals.github.io/wiki/configuration/#luarcjson-file) file in your project root to include those paths.

> For whatever reason they forked my plugin, made objectively worse native codegen, and then PR'd it to [LLS-Addons](https://github.com/LuaLS/LLS-Addons) which is a vscode addon viewer.

It would be great if all of this was included in the README file
